spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      database: test
      host: 47.94.169.30
      port: 17027
  redis:
    host: 47.94.169.30
    database: 0
    port: 6001
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG


# Jwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

