spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
